name: Update README 2016 ⭐
on:
  push:
    paths:
      - 2016/**
      - .github/workflows/readme-2016.yml
  workflow_dispatch:

jobs:
  readme-2017:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: miam-miam100/advent-readme-stars@20e208a0ba6867d1919798cbcc78c453460fa356
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2016
          tableMarker: '<!--- advent_readme_stars_2016 table --->'
          solutionLocations: '{yyyy}/aoc2016/day{d}.cs'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README stars of 2016
