name: Update README 2020 ⭐
on:
  push:
    paths:
      - 2020/**
      - .github/workflows/readme-2020.yml
  workflow_dispatch:

jobs:
  readme-2020:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: miam-miam100/advent-readme-stars@20e208a0ba6867d1919798cbcc78c453460fa356
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2020
          tableMarker: '<!--- advent_readme_stars_2020 table --->'
          solutionLocations: '{yyyy}/aoc2020/day{d}.cs'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README stars of 2020
