name: Update README 2021 ⭐
on:
  push:
    paths:
      - 2021/**
      - .github/workflows/readme-2021.yml
  workflow_dispatch:

jobs:
  readme-2021:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: miam-miam100/advent-readme-stars@20e208a0ba6867d1919798cbcc78c453460fa356
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2021
          tableMarker: '<!--- advent_readme_stars_2021 table --->'
          solutionLocations: '{yyyy}/aoc2021/day{d}.cs'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README stars of 2021
