name: Update README 2022 ⭐
on:
  push:
    paths:
      - 2022/**
  workflow_dispatch:

jobs:
  readme-2022:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: miam-miam100/advent-readme-stars@20e208a0ba6867d1919798cbcc78c453460fa356
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2022
          tableMarker: '<!--- advent_readme_stars_2022 table --->'
          solutionLocations: '{yyyy}/day{dd}/day{dd}/day{dd}.py'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README stars of 2020
