name: Update README 2024 ⭐
on:
  push:
    paths:
      - 2024/**
      - .github/workflows/readme-2024.yml
  workflow_dispatch:

jobs:
  readme-2024:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: miam-miam100/advent-readme-stars@20e208a0ba6867d1919798cbcc78c453460fa356
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2024
          tableMarker: '<!--- advent_readme_stars_2024 table --->'
          solutionLocations: '{yyyy}/day{d}/day{d}.py'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README stars of 2024
